import type {
  Profile,
  Service,
  Client,
  Booking,
  AvailabilityRule,
  DateOverride,
  Staff,
  IntakeForm,
  NotificationTemplate,
  NotificationLogEntry,
} from "@/lib/types";

// Dynamic date helpers
function getIsoDate(daysOffset: number, hours = 10, minutes = 0) {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
}

export const MOCK_PROFILE: Profile = {
  id: "demo-portfolio-id",
  username: "ironandink",
  profession: "tattoo_artist",
  businessName: "Iron & Ink Tattoo Studio",
  bio: "Custom tattoo studio in Austin, TX. Specialising in blackwork, fine line, and Japanese traditional. Walk-ins welcome on Saturdays.",
  photoUrl: null,
  location: "Austin, TX",
  contactEmail: "alex@ironandink.com",
  contactPhone: "+1 (512) 555-0192",
  accentColor: "teal",
  showSocialLinks: true,
  advanceBookingDays: 60,
  minNoticeHours: 24,
  bufferMinutes: 15,
  depositDefaultPercent: 30,
  cancellationPolicy: "Cancellations within 48 hours forfeit the deposit.",
  refundPolicy: "Full refund if cancelled more than 48 hours before appointment.",
  stripeAccountId: "acct_demo12345",
  stripeCustomerId: null,
  stripeSubscriptionId: null,
  subscriptionPlan: "pro",
  subscriptionStatus: "active",
  proNotifyNewBooking: true,
  proNotifyCancellation: true,
  proNotifyPayment: true,
  onboardingStep: 4,
  onboardingCompleted: true,
  createdAt: "2026-01-01T00:00:00Z",
};

export const MOCK_SERVICES: Service[] = [
  {
    id: "srv-1",
    profileId: "demo-portfolio-id",
    name: "Custom Tattoo Consultation",
    description: "Discuss design ideas, sizing, placement, and estimate pricing for custom artwork.",
    durationMinutes: 45,
    priceCents: 5000,
    depositRequired: true,
    depositAmountCents: 2000,
    maxDailyLimit: 4,
    bufferMinutes: 15,
    active: true,
    sortOrder: 1,
    extra: {},
  },
  {
    id: "srv-2",
    profileId: "demo-portfolio-id",
    name: "Flash Tattoo Session",
    description: "Pre-designed flash art from studio flash books. Size up to 4 inches.",
    durationMinutes: 90,
    priceCents: 18000,
    depositRequired: true,
    depositAmountCents: 5000,
    maxDailyLimit: 3,
    bufferMinutes: 15,
    active: true,
    sortOrder: 2,
    extra: {},
  },
  {
    id: "srv-3",
    profileId: "demo-portfolio-id",
    name: "Full Day Sleeve Session",
    description: "6-hour intensive shading, lining, and color packing for large scale projects.",
    durationMinutes: 360,
    priceCents: 85000,
    depositRequired: true,
    depositAmountCents: 20000,
    maxDailyLimit: 1,
    bufferMinutes: 30,
    active: true,
    sortOrder: 3,
    extra: {},
  },
  {
    id: "srv-4",
    profileId: "demo-portfolio-id",
    name: "Touch-up Session",
    description: "Free touch-ups within 60 days for existing clients.",
    durationMinutes: 45,
    priceCents: 0,
    depositRequired: false,
    depositAmountCents: 0,
    maxDailyLimit: 2,
    bufferMinutes: 15,
    active: true,
    sortOrder: 4,
    extra: {},
  },
  {
    id: "srv-5",
    profileId: "demo-portfolio-id",
    name: "Cover-up Assessment",
    description: "Evaluate existing tattoo for laser fading or custom cover-up design planning.",
    durationMinutes: 60,
    priceCents: 7500,
    depositRequired: true,
    depositAmountCents: 2500,
    maxDailyLimit: 2,
    bufferMinutes: 15,
    active: true,
    sortOrder: 5,
    extra: {},
  },
];

export const MOCK_CLIENTS: Client[] = [
  {
    id: "cli-1",
    profileId: "demo-portfolio-id",
    name: "Sarah Connor",
    email: "sarah.connor@example.com",
    phone: "(512) 555-0123",
    notes: "Prefers fine line botanical work on forearms.",
    noShowCount: 0,
    createdAt: "2026-01-10T12:00:00Z",
    totalSessions: 4,
    totalSpentCents: 92000,
    lastVisitAt: getIsoDate(-3),
  },
  {
    id: "cli-2",
    profileId: "demo-portfolio-id",
    name: "Marcus Vance",
    email: "marcus.vance@example.com",
    phone: "(512) 555-0144",
    notes: "Working on full Japanese sleeve (dragon & waves).",
    noShowCount: 0,
    createdAt: "2026-01-15T14:30:00Z",
    totalSessions: 3,
    totalSpentCents: 170000,
    lastVisitAt: getIsoDate(-10),
  },
  {
    id: "cli-3",
    profileId: "demo-portfolio-id",
    name: "Elena Rostova",
    email: "elena.r@example.com",
    phone: "(512) 555-0188",
    notes: "Sensitive skin. Uses numbing cream before sessions.",
    noShowCount: 0,
    createdAt: "2026-02-01T09:15:00Z",
    totalSessions: 2,
    totalSpentCents: 36000,
    lastVisitAt: getIsoDate(0),
  },
  {
    id: "cli-4",
    profileId: "demo-portfolio-id",
    name: "David Miller",
    email: "d.miller@example.com",
    phone: "(512) 555-0199",
    notes: "Micro-realism portrait client.",
    noShowCount: 1,
    createdAt: "2026-02-20T16:00:00Z",
    totalSessions: 1,
    totalSpentCents: 18000,
    lastVisitAt: getIsoDate(2),
  },
  {
    id: "cli-5",
    profileId: "demo-portfolio-id",
    name: "Chloe Bennett",
    email: "chloe.b@example.com",
    phone: "(512) 555-0211",
    notes: "Referred by Sarah Connor. Wants geometric wrist piece.",
    noShowCount: 0,
    createdAt: "2026-03-05T11:45:00Z",
    totalSessions: 2,
    totalSpentCents: 23000,
    lastVisitAt: getIsoDate(5),
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  // Today's Bookings
  {
    id: "bk-today-1",
    profileId: "demo-portfolio-id",
    serviceId: "srv-2",
    clientId: "cli-3",
    staffId: "stf-1",
    startAt: getIsoDate(0, 10, 0),
    endAt: getIsoDate(0, 11, 30),
    status: "confirmed",
    totalPriceCents: 18000,
    depositAmountCents: 5000,
    depositPaid: true,
    locationAddress: "Studio Room A - Austin, TX",
    clientNotes: "Flash #42 from the summer flash sheet.",
    proNotes: "Stencil prepped. Need black & grey wash ink.",
    recurringGroupId: null,
    clientName: "Elena Rostova",
    serviceName: "Flash Tattoo Session",
  },
  {
    id: "bk-today-2",
    profileId: "demo-portfolio-id",
    serviceId: "srv-1",
    clientId: "cli-1",
    staffId: "stf-1",
    startAt: getIsoDate(0, 14, 0),
    endAt: getIsoDate(0, 14, 45),
    status: "confirmed",
    totalPriceCents: 5000,
    depositAmountCents: 2000,
    depositPaid: true,
    locationAddress: "Studio Room A - Austin, TX",
    clientNotes: "Discussing shoulder piece to match existing sleeve.",
    proNotes: "Review reference photos provided via email.",
    recurringGroupId: null,
    clientName: "Sarah Connor",
    serviceName: "Custom Tattoo Consultation",
  },

  // Upcoming Bookings
  {
    id: "bk-next-1",
    profileId: "demo-portfolio-id",
    serviceId: "srv-3",
    clientId: "cli-2",
    staffId: "stf-1",
    startAt: getIsoDate(1, 11, 0),
    endAt: getIsoDate(1, 17, 0),
    status: "confirmed",
    totalPriceCents: 85000,
    depositAmountCents: 20000,
    depositPaid: true,
    locationAddress: "Studio Room A - Austin, TX",
    clientNotes: "Session 4 for Japanese sleeve background shading.",
    proNotes: "Prepare coil machine #2 and Magnum 15 needles.",
    recurringGroupId: null,
    clientName: "Marcus Vance",
    serviceName: "Full Day Sleeve Session",
  },
  {
    id: "bk-next-2",
    profileId: "demo-portfolio-id",
    serviceId: "srv-4",
    clientId: "cli-4",
    staffId: "stf-2",
    startAt: getIsoDate(2, 13, 0),
    endAt: getIsoDate(2, 13, 45),
    status: "confirmed",
    totalPriceCents: 0,
    depositAmountCents: 0,
    depositPaid: true,
    locationAddress: "Studio Room B - Austin, TX",
    clientNotes: "Minor touchup on forearm lines.",
    proNotes: "",
    recurringGroupId: null,
    clientName: "David Miller",
    serviceName: "Touch-up Session",
  },
  {
    id: "bk-next-3",
    profileId: "demo-portfolio-id",
    serviceId: "srv-5",
    clientId: "cli-5",
    staffId: "stf-1",
    startAt: getIsoDate(5, 15, 0),
    endAt: getIsoDate(5, 16, 0),
    status: "pending",
    totalPriceCents: 7500,
    depositAmountCents: 2500,
    depositPaid: false,
    locationAddress: "Studio Room A - Austin, TX",
    clientNotes: "Covering up an old wrist initial from college.",
    proNotes: "Needs photo of old tattoo under bright lighting.",
    recurringGroupId: null,
    clientName: "Chloe Bennett",
    serviceName: "Cover-up Assessment",
  },

  // Past Bookings for Analytics & History
  {
    id: "bk-past-1",
    profileId: "demo-portfolio-id",
    serviceId: "srv-3",
    clientId: "cli-1",
    staffId: "stf-1",
    startAt: getIsoDate(-3, 11, 0),
    endAt: getIsoDate(-3, 17, 0),
    status: "completed",
    totalPriceCents: 85000,
    depositAmountCents: 20000,
    depositPaid: true,
    locationAddress: "Studio Room A - Austin, TX",
    clientNotes: "",
    proNotes: "Completed upper arm lining & shading.",
    recurringGroupId: null,
    clientName: "Sarah Connor",
    serviceName: "Full Day Sleeve Session",
  },
  {
    id: "bk-past-2",
    profileId: "demo-portfolio-id",
    serviceId: "srv-2",
    clientId: "cli-2",
    staffId: "stf-1",
    startAt: getIsoDate(-6, 14, 0),
    endAt: getIsoDate(-6, 15, 30),
    status: "completed",
    totalPriceCents: 18000,
    depositAmountCents: 5000,
    depositPaid: true,
    locationAddress: "Studio Room A - Austin, TX",
    clientNotes: "",
    proNotes: "",
    recurringGroupId: null,
    clientName: "Marcus Vance",
    serviceName: "Flash Tattoo Session",
  },
  {
    id: "bk-past-3",
    profileId: "demo-portfolio-id",
    serviceId: "srv-1",
    clientId: "cli-5",
    staffId: "stf-2",
    startAt: getIsoDate(-10, 12, 0),
    endAt: getIsoDate(-10, 12, 45),
    status: "completed",
    totalPriceCents: 5000,
    depositAmountCents: 2000,
    depositPaid: true,
    locationAddress: "Studio Room B - Austin, TX",
    clientNotes: "",
    proNotes: "",
    recurringGroupId: null,
    clientName: "Chloe Bennett",
    serviceName: "Custom Tattoo Consultation",
  },
];

export const MOCK_AVAILABILITY: AvailabilityRule[] = [
  { id: "av-1", profileId: "demo-portfolio-id", weekday: 0, isOpen: false, startTime: "09:00", endTime: "17:00", breaks: [] },
  { id: "av-2", profileId: "demo-portfolio-id", weekday: 1, isOpen: false, startTime: "09:00", endTime: "17:00", breaks: [] },
  {
    id: "av-3",
    profileId: "demo-portfolio-id",
    weekday: 2,
    isOpen: true,
    startTime: "10:00",
    endTime: "18:00",
    breaks: [{ id: "brk-1", startTime: "13:00", endTime: "14:00" }],
  },
  {
    id: "av-4",
    profileId: "demo-portfolio-id",
    weekday: 3,
    isOpen: true,
    startTime: "10:00",
    endTime: "18:00",
    breaks: [{ id: "brk-2", startTime: "13:00", endTime: "14:00" }],
  },
  {
    id: "av-5",
    profileId: "demo-portfolio-id",
    weekday: 4,
    isOpen: true,
    startTime: "10:00",
    endTime: "18:00",
    breaks: [{ id: "brk-3", startTime: "13:00", endTime: "14:00" }],
  },
  {
    id: "av-6",
    profileId: "demo-portfolio-id",
    weekday: 5,
    isOpen: true,
    startTime: "10:00",
    endTime: "19:00",
    breaks: [{ id: "brk-4", startTime: "13:00", endTime: "14:00" }],
  },
  {
    id: "av-7",
    profileId: "demo-portfolio-id",
    weekday: 6,
    isOpen: true,
    startTime: "11:00",
    endTime: "17:00",
    breaks: [],
  },
];

export const MOCK_DATE_OVERRIDES: DateOverride[] = [];

export const MOCK_STAFF: Staff[] = [
  {
    id: "stf-1",
    profileId: "demo-portfolio-id",
    userId: "demo-portfolio-id",
    name: "Alex Reed",
    email: "alex@ironandink.com",
    role: "owner",
    serviceIds: ["srv-1", "srv-2", "srv-3", "srv-5"],
    bookingCount: 12,
  },
  {
    id: "stf-2",
    profileId: "demo-portfolio-id",
    userId: null,
    name: "Maya Lin",
    email: "maya@ironandink.com",
    role: "staff",
    serviceIds: ["srv-1", "srv-2", "srv-4"],
    bookingCount: 5,
  },
];

export const MOCK_INTAKE_FORM: IntakeForm = {
  id: "form-1",
  profileId: "demo-portfolio-id",
  serviceId: null,
  name: "Tattoo Health & Consent Form",
  fields: [
    {
      id: "fld-1",
      formId: "form-1",
      label: "Medical conditions or skin allergies",
      fieldType: "short_text",
      options: [],
      required: true,
      sortOrder: 1,
      isWaiver: false,
      requiresSignature: false,
      waiverText: null,
    },
    {
      id: "fld-2",
      formId: "form-1",
      label: "Desired tattoo placement on body",
      fieldType: "short_text",
      options: [],
      required: true,
      sortOrder: 2,
      isWaiver: false,
      requiresSignature: false,
      waiverText: null,
    },
    {
      id: "fld-3",
      formId: "form-1",
      label: "Detailed design description & style preference",
      fieldType: "long_text",
      options: [],
      required: false,
      sortOrder: 3,
      isWaiver: false,
      requiresSignature: false,
      waiverText: null,
    },
    {
      id: "fld-4",
      formId: "form-1",
      label: "I confirm I am over 18 years of age and consent to tattoo procedures.",
      fieldType: "checkbox",
      options: [],
      required: true,
      sortOrder: 4,
      isWaiver: true,
      requiresSignature: true,
      waiverText:
        "By signing below, I acknowledge that tattooing is a permanent process and I follow all aftercare instructions.",
    },
  ],
};

export const MOCK_NOTIFICATION_TEMPLATES: NotificationTemplate[] = [
  {
    id: "nt-1",
    profileId: "demo-portfolio-id",
    type: "booking_confirmation",
    channel: "email",
    enabled: true,
    subject: "Appointment Confirmed — Iron & Ink Studio",
    body: "Hi {client_name}, your appointment for {service_name} on {start_time} is confirmed! Deposit of ${deposit_amount} received.",
  },
  {
    id: "nt-2",
    profileId: "demo-portfolio-id",
    type: "reminder_24h",
    channel: "sms",
    enabled: true,
    subject: "Reminder: Tattoo Appointment Tomorrow",
    body: "Reminder: You have a tattoo appointment tomorrow at {start_time}. Please ensure you are well hydrated and ate beforehand.",
  },
];

export const MOCK_NOTIFICATION_LOG: NotificationLogEntry[] = [
  {
    id: "log-1",
    profileId: "demo-portfolio-id",
    bookingId: "bk-today-1",
    clientId: "cli-3",
    clientName: "Elena Rostova",
    type: "reminder_24h",
    channel: "sms",
    status: "sent",
    errorMessage: null,
    sentAt: getIsoDate(-1, 10, 0),
  },
  {
    id: "log-2",
    profileId: "demo-portfolio-id",
    bookingId: "bk-today-2",
    clientId: "cli-1",
    clientName: "Sarah Connor",
    type: "booking_confirmation",
    channel: "email",
    status: "sent",
    errorMessage: null,
    sentAt: getIsoDate(-2, 14, 30),
  },
];
